### ISSUE TITLE
README example doesn't work

### ISSUE THREAD

**Issue by Navgeet** [callmeal/Flickr4Java#110] opened 2014-10-29 06:02 UTC
```java
Flickr f = new Flickr(apiKey, secret, new REST());
TestInterface testInterface = f.getTestInterface();
Collection results = testInterface.echo(Collections.EMPTY_MAP);
```

This code throws the exception:

`com.flickr4java.flickr.FlickrException: 100: Invalid API Key (Key has invalid format)
 at com.flickr4java.flickr.test.TestInterface.echo (TestInterface.java:59)`

**Comment by liosha2007** [comment] 2015-01-10 06:36
Hi! I use this sources

```
        String apiKey = "real api";
        String apiSecret = "real secret";
        File file = new File("path to logo_en.png");
        Flickr flickr = new Flickr(apiKey, apiSecret, new REST());
        Uploader uploader = flickr.getUploader();
        UploadMetaData uploadMetaData = new UploadMetaData();
        String upload = uploader.upload(file, uploadMetaData);
```

And I have got exception
com.flickr4java.flickr.FlickrException: 100: Invalid API Key (Key has invalid format)
	at com.flickr4java.flickr.uploader.Uploader.postPhoto(Uploader.java:195)
	at com.flickr4java.flickr.uploader.Uploader.upload(Uploader.java:122)
	at com.flickr4java.flickr.uploader.Uploader.upload(Uploader.java:102)

But with this keys I can get recent photos without problem. Maybe I should configure my flickr account for upload photos...

**Comment by boncey** [comment] 2015-08-02 17:04
Hi, I'm not sure if this is a problem at this end or at your end so am closing it.
Please leave a comment if it's still a problem.

**Comment by shashank-lst** [comment] 2015-10-29 16:15
Hi, I'm also getting same error. I'm trying uploader to upload image same as of @liosha2007.

Any solutions?

**Comment by boncey** [comment] 2015-11-02 09:46
OK, I'll try to retest it this weekend.
Can you post any example code please?

**Comment by jwlee0208** [comment] 2015-11-11 05:28
Hi, I'm facing same error, too. 
I don't know how can I solve this problem..
Here is sample code. 

    public String uploadPhotoList(MultipartFile attachFile){
        
        InputStream is = null;
        String responseStr = "";
        Flickr f = new Flickr(apiKey, sharedSecret, new REST());

        try {
            is = attachFile.getInputStream();
            
            Tika chkFileExt = new Tika();
            String chkFileExtStr = "";
            try {
                chkFileExtStr = chkFileExt.detect(is).toLowerCase();
            } catch (IOException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
                responseStr = "error";
            }

            UploadMetaData metaData = new UploadMetaData();
            metaData.setContentType(attachFile.getContentType());
            metaData.setDescription("test");
            metaData.setFilemimetype(chkFileExtStr);
            metaData.setFilename(attachFile.getName());
            metaData.setPublicFlag(true);
            metaData.setHidden(false);
            metaData.setSafetyLevel(Flickr.SAFETYLEVEL_SAFE);
            metaData.setTitle("test");  
            metaData.setAsync(false);
            metaData.setFamilyFlag(false);
            metaData.setFriendFlag(true);
            metaData.setTags(null);
            Uploader uploader = new Uploader(apiKey, sharedSecret);
            
            try {
                responseStr = uploader.upload(is, metaData);
            } catch (FlickrException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
                responseStr = "error";
            }            
        } catch (IOException e1) {
            // TODO Auto-generated catch block
            e1.printStackTrace();
            responseStr = "error";
        }
   
        return responseStr;
    }

**Comment by LaercioMetzner** [comment] 2015-12-22 11:41
I've just got the same error. Any help would be appreciated.

**Comment by boncey** [comment] 2015-12-22 11:44
I've been struggling to find time to look at this but I am free over Christmas so will take a look then.

**Comment by LaercioMetzner** [comment] 2015-12-22 18:27
Darren Greaves, don't waste your Christmas night working, celebrate with your family instead :) . I have found that right before flickr4java sends the post request to https://up.flickr.com/services/upload/, the auth object is null at the RequestContext object, even if we had already set it with flickr.setAuth(auth). Then as an alternative workaround, I'm setting RequestContext's auth attribute before using the uploader, maybe it's not the best practice, but it's working for now. My code is like this:

```java
		File hotGirl = new File("C:\\testpictures\\hotgirl.jpg");
		// Assume there is an object called auth that's a valid instance of Auth
		RequestContext.getRequestContext().setAuth(auth);
		// Assume there is an object called flickr that's a valid instance of Flickr
		Uploader uploader = flickr.getUploader();
		uploader.upload(hotGirl, metaData);
		System.out.println("Worked fine");
```

**Comment by boncey** [comment] 2015-12-22 21:36
> don't waste your Christmas night working, celebrate with your family instead

Hehe, that's good advice thanks!
I'm sure I'll find some free time to take a look when I'm not celebrating.

**Comment by boncey** [comment] 2015-12-31 15:19
I've had a look at this now.

Thank you @LaercioMetzner for your investigative work.
You are right, you need to call `RequestContext.getRequestContext().setAuth(auth);` before uploading.
This is the same as for any Flickr4Java signed call.

The `com.flickr4java.flickr.util.FileAuthStore` class can be helpful with managing this.

So, I'm closing this bug now - the solution to the problem is to call `RequestContext.getRequestContext().setAuth(auth);` before uploading.

**Closed by boncey** 2015-12-31 15:19 UTC

**Comment by jwlee0208** [comment] 2016-01-21 09:59
Thx. 
Problem is solved.
